# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 21:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temprature', models.FloatField(default=None)),
                ('humidity', models.FloatField(default=None)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
