# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 22:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='humidity',
            field=models.FloatField(default=None, validators=[django.core.validators.MaxValueValidator(65), django.core.validators.MinValueValidator(35)]),
        ),
        migrations.AlterField(
            model_name='weather',
            name='temprature',
            field=models.FloatField(default=None, validators=[django.core.validators.MaxValueValidator(28), django.core.validators.MinValueValidator(19)]),
        ),
    ]
